### ISSUE TITLE
Error out on shorthands (stylelint-declaration-strict-value)

### ISSUE THREAD

**Issue by satazor** [moxystudio/stylelint-config#56]
We are using `stylelint-declaration-strict-value` to forbid the usage of plain values in certain props, like `color`.

However, it's not working correctly for `background` and other shorthands. Perhaps we can use [`declaration-property-value-blacklist`](https://stylelint.io/user-guide/rules/declaration-property-value-blacklist) to fix that.

**Comment by jdiogopeixoto** [comment]
@satazor `stylelint-declaration-strict-value` is not checking the `background` property.
https://github.com/moxystudio/stylelint-config/blob/5e4422730c9da6a4ae20308eb2164fd86dbe0b89/rules/declaration-strict-value.js#L5-L12

Maybe we can add some more properties that have color as an option?
